language: python

python:

  - "2.7"

install:
  - pip install pytest

script: 

  - python hello.py
  - py.test -v -rs hello_test.py


notifications:
  email:
    recipients:
      - tatyperson22@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
